
features_dict = {
    "ennepred" : ["pred_e_type_" + str(n) for n in range(1, 10)],
    "mbtipred" : ["introverted_pred", "intuitive_pred", "thinking_pred", "perceiving_pred"],
    "medianlower": ["agreeableness_median_lower", "conscientiousness_median_lower", "extraversion_median_lower", "neuroticism_median_lower", "openness_median_lower"],
    "medianhigher": ["agreeableness_median_higher", "conscientiousness_median_higher", "extraversion_median_higher", "neuroticism_median_higher", "openness_median_higher"],
    "quartilehigher": ["agreeableness_quartile_higher", "conscientiousness_quartile_higher", "extraversion_quartile_higher", "neuroticism_quartile_higher", "openness_quartile_higher"],
    "quartilemiddle": ["agreeableness_quartile_middle", "conscientiousness_quartile_middle", "extraversion_quartile_middle", "neuroticism_quartile_middle", "openness_quartile_middle"],
    "quartilelower": ["agreeableness_quartile_lower", "conscientiousness_quartile_lower", "extraversion_quartile_lower", "neuroticism_quartile_lower", "openness_quartile_lower"],
    "liwc": ["WC", "WPS", "Sixltr", "Dic", "funct", "pronoun", "ppron", "i", "we", "you", "shehe", "they", "ipron", "article", "verb", "auxverb", "past", "present", "future", "adverb", "preps", "conj", "negate", "quant", "number", "swear", "social", "family", "friend", "humans", "affect", "posemo", "negemo", "anx", "anger", "sad", "cogmech", "insight", "cause", "discrep", "tentat", "certain", "inhib", "incl", "excl", "percept", "see", "hear", "feel", "bio", "body", "health", "sexual", "ingest", "relativ", "motion", "space", "time", "work", "achieve", "leisure", "home", "money", "relig", "death", "assent", "nonfl", "filler", "AllPunc", "Period", "Comma", "Colon", "SemiC", "QMark", "Exclam", "Dash", "Quote", "Apostro", "Parenth", "OtherP"],
    "liwc_agree_cols": ["Dic", "funct", "pronoun", "ppron", "i", "we", "you", "ipron", "verb", "present", "adverb", "conj", "negate", "swear", "social", "friend", "humans", "posemo", "negemo", "anger", "cogmech", "certain", "incl", "excl", "feel", "sexual", "time", "work", "Exclam"],
    "liwc_consc_cols": ["negate", "swear", "family", "negemo", "anger", "sad", "tentat", "excl", "sexual", "ingest", "motion", "home", "relig", "Comma", "QMark", "Exclam"],
    "liwc_open_cols" : ["Sixltr", "preps", "insight", "incl", "health", "time", "leisure", "QMark", "Exclam"],
    "liwc_extra_cols" : ["ppron", "we", "you", "shehe", "negate", "social", "family", "friend", "humans", "anger", "tentat", "incl", "excl", "AllPunc", "Apostro", "OtherP"],
    "liwc_neuro_cols": ["i", "you", "past", "adverb", "preps", "social", "humans", "anx", "cause", "hear", "health", "nonfl", "SemiC", "QMark", "Exclam", "Apostro", "Parenth"],
    "liwc_big5_cols": ["AllPunc", "excl", "home", "work", "family", "preps", "insight", "sexual", "OtherP", "swear", "adverb", "ingest", "leisure", "hear", "time", "relig", "Comma", "anx", "verb", "humans", "shehe", "ipron", "cogmech", "health", "posemo", "motion", "SemiC", "present", "social", "you", "tentat", "nonfl", "negate", "Sixltr", "sad", "feel", "Parenth", "Dic", "past", "ppron", "we", "conj", "incl", "Exclam", "cause", "friend", "funct", "pronoun", "anger", "Apostro", "certain", "negemo", "QMark", "i"],
    "liwc_ei_cols": ["affect", "AllPunc", "anger", "anx", "article", "assent", "auxverb", "bio", "body", "cogmech", "Colon", "Comma", "conj", "Dash", "death", "Dic", "discrep", "Exclam", "family", "feel", "filler", "friend", "funct", "future", "health", "humans", "i", "incl", "inhib", "leisure", "money", "motion", "negate", "negemo", "number", "OtherP", "Parenth", "posemo", "ppron", "present", "pronoun", "quant", "relig", "sad", "see", "sexual", "shehe", "social", "swear", "tentat", "verb", "we", "you"],
    "liwc_sn_cols": ["achieve", "Apostro", "article", "assent", "bio", "body", "cause", "certain", "cogmech", "Colon", "Comma", "death", "Exclam", "family", "filler", "friend", "health", "hear", "home", "i", "ingest", "inhib", "insight", "ipron", "leisure", "motion", "number", "past", "percept", "ppron", "preps", "pronoun", "quant", "Quote", "relativ", "relig", "sad", "see", "shehe", "Sixltr", "swear", "time", "verb", "we", "WPS"],
    "liwc_tf_cols": ["achieve", "adverb", "affect", "anger", "anx", "Apostro", "article", "assent", "auxverb", "bio", "body", "cause", "certain", "cogmech", "Colon", "conj", "Dash", "death", "Dic", "discrep", "excl", "Exclam", "family", "feel", "filler", "friend", "funct", "future", "health", "hear", "home", "humans", "i", "incl", "inhib", "insight", "ipron", "leisure", "money", "negate", "nonfl", "number", "OtherP", "past", "percept", "posemo", "ppron", "present", "pronoun", "QMark", "quant", "Quote", "relativ", "sad", "see", "sexual", "shehe", "Sixltr", "social", "space", "swear", "they", "time", "verb", "WC", "we", "work", "WPS", "you"],
    "liwc_jp_cols": ["achieve", "adverb", "affect", "anger", "anx", "assent", "conj", "Dash", "death", "Dic", "discrep", "excl", "Exclam", "family", "feel", "filler", "funct", "health", "hear", "home", "i", "incl", "ingest", "inhib", "ipron", "leisure", "money", "motion", "negate", "negemo", "nonfl", "OtherP", "past", "percept", "ppron", "preps", "pronoun", "QMark", "relativ", "relig", "see", "sexual", "shehe", "social", "space", "swear", "tentat", "they", "time", "WC", "we", "work", "WPS", "you"],
    "liwc_mbti_cols" : ["achieve", "adverb", "affect", "AllPunc", "anger", "anx", "Apostro", "article", "assent", "auxverb", "bio", "body", "cause", "certain", "cogmech", "Colon", "Comma", "conj", "Dash", "death", "Dic", "discrep", "excl", "Exclam", "family", "feel", "filler", "friend", "funct", "future", "health", "hear", "home", "humans", "i", "incl", "ingest", "inhib", "insight", "ipron", "leisure", "money", "motion", "negate", "negemo", "nonfl", "number", "OtherP", "Parenth", "past", "percept", "posemo", "ppron", "preps", "present", "pronoun", "QMark", "quant", "Quote", "relativ", "relig", "sad", "see", "sexual", "shehe", "Sixltr", "social", "space", "swear", "tentat", "they", "time", "verb", "WC", "we", "work", "WPS", "you"],
    "liwc_WC" : ["WC"],
    "liwc_WPS" : ["WPS"],
    "liwc_Sixltr" : ["Sixltr"],
    "liwc_Dic" : ["Dic"],
    "liwc_funct" : ["funct"],
    "liwc_pronoun" : ["pronoun"],
    "liwc_ppron" : ["ppron"],
    "liwc_i" : ["i"],
    "liwc_we" : ["we"],
    "liwc_you" : ["you"],
    "liwc_shehe" : ["shehe"],
    "liwc_they" : ["they"],
    "liwc_ipron" : ["ipron"],
    "liwc_article" : ["article"],
    "liwc_verb" : ["verb"],
    "liwc_auxverb" : ["auxverb"],
    "liwc_past" : ["past"],
    "liwc_present" : ["present"],
    "liwc_future" : ["future"],
    "liwc_adverb" : ["adverb"],
    "liwc_preps" : ["preps"],
    "liwc_conj" : ["conj"],
    "liwc_negate" : ["negate"],
    "liwc_quant" : ["quant"],
    "liwc_number" : ["number"],
    "liwc_swear" : ["swear"],
    "liwc_social" : ["social"],
    "liwc_family" : ["family"],
    "liwc_friend" : ["friend"],
    "liwc_humans" : ["humans"],
    "liwc_affect" : ["affect"],
    "liwc_posemo" : ["posemo"],
    "liwc_negemo" : ["negemo"],
    "liwc_anx" : ["anx"],
    "liwc_anger" : ["anger"],
    "liwc_sad" : ["sad"],
    "liwc_cogmech" : ["cogmech"],
    "liwc_insight" : ["insight"],
    "liwc_cause" : ["cause"],
    "liwc_discrep" : ["discrep"],
    "liwc_tentat" : ["tentat"],
    "liwc_certain" : ["certain"],
    "liwc_inhib" : ["inhib"],
    "liwc_incl" : ["incl"],
    "liwc_excl" : ["excl"],
    "liwc_percept" : ["percept"],
    "liwc_see" : ["see"],
    "liwc_hear" : ["hear"],
    "liwc_feel" : ["feel"],
    "liwc_bio" : ["bio"],
    "liwc_body" : ["body"],
    "liwc_health" : ["health"],
    "liwc_sexual" : ["sexual"],
    "liwc_ingest" : ["ingest"],
    "liwc_relativ" : ["relativ"],
    "liwc_motion" : ["motion"],
    "liwc_space" : ["space"],
    "liwc_time" : ["time"],
    "liwc_work" : ["work"],
    "liwc_achieve" : ["achieve"],
    "liwc_leisure" : ["leisure"],
    "liwc_home" : ["home"],
    "liwc_money" : ["money"],
    "liwc_relig" : ["relig"],
    "liwc_death" : ["death"],
    "liwc_assent" : ["assent"],
    "liwc_nonfl" : ["nonfl"],
    "liwc_filler" : ["filler"],
    "liwc_AllPunc" : ["AllPunc"],
    "liwc_Period" : ["Period"],
    "liwc_Comma" : ["Comma"],
    "liwc_Colon" : ["Colon"],
    "liwc_SemiC" : ["SemiC"],
    "liwc_QMark" : ["QMark"],
    "liwc_Exclam" : ["Exclam"],
    "liwc_Dash" : ["Dash"],
    "liwc_Quote" : ["Quote"],
    "liwc_Apostro" : ["Apostro"],
    "liwc_Parenth" : ["Parenth"],
    "liwc_OtherP" : ["OtherP"],
    "authors_least_reddit" : ["AmazonUnder25", "AnimationClub", "AnswerReddit", "ArmedBirds", "Autoimmune", "CricketShitpost", "FuckToken", "GGM", "GoldenAgeMinecraft", "Gorb", "Haydee", "HoverROG", "IPv4orGTFO", "Ilovemyself", "ImaginaryWestworld", "InterstellarUnited", "KyloRen", "LyricInterpretations", "Midland", "OneThousandYearsAgo", "Philadelphia4Sanders", "PiratePartyUK", "RIPEarthPorn", "RoboRecall", "Spednation", "TLJH", "TaobaoGuides", "TheLastLeviathan", "ThirdEyeBlind", "ToiletDoodles", "Yishun", "blondebush", "evnova", "farm", "gamingcouples", "gmt", "liquiddnbproduction", "llamaloaf", "maltheism", "nsfwxpost", "riskyclick", "sock", "submissive", "tarantulasinhats", "teekaytank", "the_ninth_age", "unimog", "william", "woodstoves", "wyeoak"],
    "authors_most_reddit" : ["AdviceAnimals", "Android", "AskMen", "AskReddit", "AskWomen", "CFB", "CasualConversation", "Christianity", "DotA2", "ENFP", "Futurology", "INTP", "MLPLounge", "OkCupid", "Overwatch", "PurplePillDebate", "Showerthoughts", "SquaredCircle", "The_Donald", "TumblrInAction", "WTF", "anime", "childfree", "entp", "europe", "ffxiv", "funny", "gaming", "gifs", "infj", "infp", "intj", "keto", "leagueoflegends", "mbti", "movies", "nba", "news", "nfl", "pcmasterrace", "pics", "politics", "popheads", "relationships", "soccer", "teenagers", "todayilearned", "ukpolitics", "videos", "worldnews"],
    "comments_least_reddit" : ["AmazonUnder25", "AnimationClub", "AnswerReddit", "ArmedBirds", "Autoimmune", "CricketShitpost", "FuckToken", "GGM", "GoldenAgeMinecraft", "Gorb", "Haydee", "HoverROG", "IPv4orGTFO", "Ilovemyself", "ImaginaryWestworld", "InterstellarUnited", "KyloRen", "LyricInterpretations", "Midland", "OneThousandYearsAgo", "Philadelphia4Sanders", "PiratePartyUK", "RIPEarthPorn", "RoboRecall", "Spednation", "TLJH", "TaobaoGuides", "TheLastLeviathan", "ThirdEyeBlind", "ToiletDoodles", "Yishun", "blondebush", "evnova", "farm", "gamingcouples", "gmt", "liquiddnbproduction", "llamaloaf", "maltheism", "nsfwxpost", "riskyclick", "sock", "submissive", "tarantulasinhats", "teekaytank", "the_ninth_age", "unimog", "william", "woodstoves", "wyeoak"],
    "comments_most_reddit" : ["AdviceAnimals", "Android", "AskMen", "AskReddit", "AskWomen", "CFB", "CasualConversation", "Christianity", "DotA2", "ENFP", "Futurology", "INTP", "MLPLounge", "OkCupid", "Overwatch", "PurplePillDebate", "Showerthoughts", "SquaredCircle", "The_Donald", "TumblrInAction", "WTF", "anime", "childfree", "entp", "europe", "ffxiv", "funny", "gaming", "gifs", "infj", "infp", "intj", "keto", "leagueoflegends", "mbti", "movies", "nba", "news", "nfl", "pcmasterrace", "pics", "politics", "popheads", "relationships", "soccer", "teenagers", "todayilearned", "ukpolitics", "videos", "worldnews"],
}